theme: yefeme
title: The Musings of Yefim Vedernikoff
author: Yefim Vedernikoff
email: hi@yef.im
description: >
  This is the place where I gather my scrambled thoughts into words.
baseurl: ""
url: "https://yef.im"
twitter_username: yefim
github_username:  yefim

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
